AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/migrate/*
    - db/schema.rb

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - config/initializers/app_config.rb
    - spec/**/*.rb
    - lib/tasks/*

Rails/Output:
  Exclude:
  - db/seeds.rb
