version: 0.2

phases:
  pre_build:
    commands:
      - echo 'export LANG=en_US.UTF-8' >> ~/.bashrc
      - echo 'export LANGUAGE=en_US.UTF-8' >> ~/.bashrc
      - echo 'export LC_ALL=en_US.UTF-8' >> ~/.bashrc

      - mysqld_safe & disown -h
      - sleep 5
      - mysql -e "grant all privileges on *.* to 'hostedidp_app'@'%' identified by 'password';"

      - redis-server & disown -h

      - echo 'export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"' >> ~/.bashrc
      - source ~/.bashrc
      - curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash
      - echo 'eval "$(rbenv init -)"' >> ~/.bashrc
      - source ~/.bashrc

      - "[ -e .ruby-version ] && rbenv install $(cat .ruby-version) --skip-existing"

      - gem install bundler
      - bundle install
      - bundle exec torba pack || true

      - cp config/validator_service.yml.dist config/validator_service.yml
      - RAILS_ENV=test bundle exec rake db:drop db:create db:schema:load
  build:
    commands:
      - RAILS_ENV=test bundle exec rake
cache:
  paths:
    - '/root/.rbenv/**/*'
    - '/var/cache/yum/x86_64/7/**/*'
    - 'tmp/**/*'
    - 'schema/**/*'
